[tool.poetry]
name = "nextdataplatform"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
duckdb = "^0.2.8"
pyarrow = "^5.0.0"
fastparquet = "^0.7.1"
pandas = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pylint = "^2.8.2"
mypy = "^0.812"
ipykernel = "^5.5.5"
black = {version = "^21.6b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
